require 'mongoid'
require 'stringex'
require 'mongoid/slug'
require 'mongoid/slug/criteria'
require 'mongoid/slug/named_scope'
require 'mongoid/slug/unique_slug'
require 'mongoid/slug/slug_id_strategy'
